-- =====================================================================
-- Oracle DB Setup Script
-- Run this script as SYSTEM or SYSDBA in SQL Developer
-- =====================================================================

-- Note: In Oracle 21c XE, the non-CDB architecture is deprecated. 
-- You are connecting to a Container DB. To simulate a "normal DB", 
-- we connect to the default Pluggable Database (XEPDB1) and create a schema.
-- In Oracle, a "schema" acts exactly like a traditional "database" in MySQL/SQL Server.

-- 1. Switch to the default pluggable database (where user data belongs)
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Clean up existing user if recreating
BEGIN
   EXECUTE IMMEDIATE 'DROP USER appuser CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/

-- 3. Create the user (this acts as the 'ccdb' database/schema)
CREATE USER appuser IDENTIFIED BY "yourpassword" DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

-- 4. Grant privileges
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE SYNONYM TO appuser;

-- =====================================================================
-- SAMPLE TABLES FOR BACKEND CORRECTIONS PORTAL
-- =====================================================================

-- Switch to the new schema
ALTER SESSION SET CURRENT_SCHEMA = appuser;

-- Table: Corrections
CREATE TABLE corrections (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket VARCHAR2(100) NOT NULL,
    query CLOB NOT NULL,
    executed_by VARCHAR2(100) NOT NULL,
    date_val DATE DEFAULT SYSDATE,
    status VARCHAR2(50) DEFAULT 'Pending',
    notes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Tickets (Sample reference table)
CREATE TABLE tickets (
    ticket_no VARCHAR2(100) PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    system_name VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Sample Data
INSERT INTO tickets (ticket_no, title, system_name) VALUES ('INC-1001', 'Fix user permissions', 'CRM');
INSERT INTO tickets (ticket_no, title, system_name) VALUES ('INC-1002', 'Update pricing table', 'Billing');

INSERT INTO corrections (ticket, query, executed_by, status, notes) 
VALUES ('INC-1001', 'UPDATE users SET role=''admin'' WHERE id=5;', 'Administrator', 'Completed', 'Requested by support');

INSERT INTO corrections (ticket, query, executed_by, status, notes) 
VALUES ('INC-1002', 'UPDATE products SET price=9.99 WHERE id=10;', 'Administrator', 'Pending', 'Waiting for approval');

COMMIT;

-- =====================================================================
-- ALL DONE!
-- Now configure the portal settings:
-- Host: localhost
-- Port: 1521
-- Service: XEPDB1  (Important: use XEPDB1, not XE)
-- User: appuser
-- Password: yourpassword
-- =====================================================================
